mqtt:
  sensor:
    - name: "Temperature"
      state_topic: "inkbird/state"
      device_class: "temperature"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.temperature }}"
    - name: "CO2"
      state_topic: "inkbird/state"
      device_class: "carbon_dioxide"
      unit_of_measurement: "ppm"
      value_template: "{{ value_json.co2 }}"
    - name: "Humidity"
      state_topic: "inkbird/state"
      device_class: "humidity"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"
    - name: "Air Pressure"
      state_topic: "inkbird/state"
      device_class: "atmospheric_pressure"
      unit_of_measurement: "hPa"
      value_template: "{{ value_json.atmospheric_pressure }}"